### PR TITLE
Converted NewEmbeddedNATSServer to a variadic options based signature…

### PR DESCRIPTION
**Pull request by davedotdev**
Converted `NewEmbeddedNATSServer` to a variadic one.

Will be a breaking change, but now the two key bits of functionality can be overridden.

Cheers,
D

### CODE REVIEW

**Review by delaneyj — CHANGES_REQUESTED** [review]
Shouldn't they be separate options in the Options Builder pattern? https://blog.matthiasbruns.com/golang-options-vs-builder-pattern#heading-the-alternative-builder-pattern

**Comment by davedotdev** [comment]
Depends on the style you want. Same outcome, different approach. 

I'll re-do it. Sigh.

**Comment by delaneyj** [comment]
I can do in the morning sigh

**Comment by davedotdev** [comment]
Le soupir.

I've added the builder pattern and an examples directory to show you how to use it. Variadic has gone and despite being more verbose, seems to make sense. Tested. Noice.

seufzen.

**Comment by delaneyj** [comment]
Fixed in separate PR, thanks though this spurred that approach!

**Pull request closed without merging**
